### PR TITLE
fix: outbound escrow accounting

### PR DESCRIPTION
**Pull request by gzeoneth**

### CODE REVIEW

**Review by yahgwai — APPROVED** [review]

**Comment by Babyking10** [comment]
good job

**Comment by nguyencothach** [comment]
on the right track, great

**Comment by JaneNguyen68** [comment]
great....!!!

**Comment by nguyencuong2505** [comment]
Everything seems to have been fixed, and I feel like that's a great thing.

**Comment by nho00** [comment]
I think this is the best of the layer2 projects I know

**Comment by Rapheal36998** [comment]
✋

**Comment by Rapheal36998** [comment]
🙏

**Comment by Rapheal36998** [comment]
✅

**Comment by Rapheal36998** [comment]
Hello

**Pull request merged**
